routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index');

Auth::routes();

Route::get('/admin', 'Admin\IndexController@index')->name('admin');
Route::get('/admin/themes', 'Admin\ThemeController@index');
Route::post('/admin/themes/set', 'Admin\ThemeController@set');

Route::get('/admin/subsystems', 'Admin\SubsystemController@index');
Route::post('/admin/subsystems/{subsystem}/install', 'Admin\SubsystemController@install');
Route::post('/admin/subsystems/{subsystem}/enable', 'Admin\SubsystemController@enable');
Route::post('/admin/subsystems/{subsystem}/disable', 'Admin\SubsystemController@disable');

Route::resource('users', 'Admin\UserController');
Route::resource('roles', 'Admin\RoleController');

app/Role.php
<?php

namespace App;

use Spatie\Permission\Models\Role as SpatieRole;

class Role extends SpatieRole
{
	public static $permissions = [
		'view dashboard',
		'create user',
	];

	protected $fillable = ['name', 'description', 'guard_name'];
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Role;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::all();
        return view('admin.roles.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $role = new Role;
        $permissions = Role::$permissions;
        return view('admin.roles.create', compact('role', 'permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'=>'required|max:40',
        ]);

        $role = Role::create($request->all());
        $role->syncPermissions($request->permissions);
        return redirect(route('roles.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        $permissions = Role::$permissions;
        // dd($role->permissions);
        return view('admin.roles.edit', compact('role', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        $this->validate($request, [
            'name'=>'required|max:40',
        ]);

        $role->update($request->all());
        $role->syncPermissions($request->permissions);
        return redirect(route('roles.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        //
        $role->delete();
        return redirect(route('roles.index'));
    }
}

resources/views/admin/roles/create.blade.php
@extends("admin.layouts.admin")

@section("content")

<h1 class="title">Create Role</h1>

<form action="{{ route('roles.store') }}" method="post">
	{{ csrf_field() }}

	@include('admin.roles.components.form')

	<div class="field is-grouped">
		<div class="control">
			<button class="button is-link">Submit</button>
		</div>
		<div class="control">
			<button class="button is-link is-light">Cancel</button>
		</div>
	</div>
</form>


@endsection

resources/views/admin/roles/edit.blade.php
@extends("admin.layouts.admin")

@section("content")

<h1 class="title">Edit Role</h1>

<form action="{{ route('roles.update', [$role->id]) }}" method="post">
	{{ csrf_field() }}
	{{ method_field('PATCH') }}

	@include('admin.roles.components.form')

	<div class="field is-grouped">
		<div class="control">
			<button class="button is-link">Submit</button>
		</div>
		<div class="control">
			<button class="button is-link is-light">Cancel</button>
		</div>
	</div>
</form>


@endsection

resources/views/admin/roles/index.blade.php
@extends("admin.layouts.admin")

@section("content")


<h1 class="title">Roles</h1>
<a class="button is-pulled-right" href="{{ route('roles.create') }}">Create Role</a>

<table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
	<thead>
		<tr>
			<td></td>
			<td>Name</td>
			<td>Description</td>
			<td>Actions</td>
		</tr>
	</thead>
	<tbody>
		@foreach($roles as $role)
		<tr>
			<td></td>
			<td>{{ $role->name }}</td>
			<td>{{ $role->description }}</td>
			<td>
				{{-- @can('update', $role) --}}
				<a href="{{ route('roles.edit', [$role->id]) }}" class="button is-primary">
					<i class="fa fa-pencil"></i>
				</a>
				{{-- @endcan --}}
				{{-- @can('delete', $role) --}}
				<form style="display: inline;" action="{{ route('roles.destroy', [$role->id]) }}" method="POST">
					{{ csrf_field() }}
					{{ method_field('DELETE') }}
					<button type="submit" class="button is-danger">
						<i class="fa fa-trash"></i>
					</button>
				</form>
				{{-- @endcan --}}
			</td>
		</tr>
		@endforeach
	</tbody>
</table>



@endsection