routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index');

Auth::routes();

Route::get('/admin', 'Admin\IndexController@index')->name('admin');
Route::get('/admin/themes', 'Admin\ThemeController@index');
Route::post('/admin/themes/set', 'Admin\ThemeController@set');

Route::get('/admin/subsystems', 'Admin\SubsystemController@index');
Route::post('/admin/subsystems/{subsystem}/install', 'Admin\SubsystemController@install');
Route::post('/admin/subsystems/{subsystem}/enable', 'Admin\SubsystemController@enable');
Route::post('/admin/subsystems/{subsystem}/disable', 'Admin\SubsystemController@disable');

Route::resource('users', 'Admin\UserController');
Route::resource('roles', 'Admin\RoleController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getRoleAttribute()
    {
        return $this->roles->first();
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use App\Role;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::with('roles')->get();
        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = new User;
        $roles = Role::all();
        return view('admin.users.create', compact('user', 'roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'=>'required|max:100',
            'email'=>'required|email',
        ]);

        $user = User::create($request->all());
        if (isset($request->role)) {
            $role = Role::find($request->role);
            $user->assignRole($role);
        }
        return redirect(route('users.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $roles = Role::all();
        return view('admin.users.edit', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $this->validate($request, [
            'name'=>'required|max:100',
            'email'=>'required|email',
        ]);

        $user->fill($request->all());
        $role = [];
        if (isset($request->role)) {
            $role[] = Role::find($request->role);
        }
        $user->syncRoles($role);
        $user->save();
        return redirect(route('users.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return redirect(route('users.index'));
    }
}

resources/views/admin/users/create.blade.php
@extends("admin.layouts.admin")

@section("content")

<h1 class="title">Create User</h1>

<form action="{{ route('users.store') }}" method="post">
	{{ csrf_field() }}

	@include('admin.users.components.form')

	<div class="field is-grouped">
		<div class="control">
			<button class="button is-link">Submit</button>
		</div>
		<div class="control">
			<button class="button is-link is-light">Cancel</button>
		</div>
	</div>
</form>


@endsection

resources/views/admin/users/edit.blade.php
@extends("admin.layouts.admin")

@section("content")

<h1 class="title">Edit User</h1>

<form action="{{ route('users.update', [$user->id]) }}" method="post">
	{{ csrf_field() }}
	{{ method_field('PATCH') }}

	@include('admin.users.components.form')

	<div class="field is-grouped">
		<div class="control">
			<button class="button is-link">Submit</button>
		</div>
		<div class="control">
			<button class="button is-link is-light">Cancel</button>
		</div>
	</div>
</form>


@endsection

resources/views/admin/users/index.blade.php
@extends("admin.layouts.admin")

@section("content")


<h1 class="title">Users</h1>
<a class="button is-pulled-right" href="{{ route('users.create') }}">Create User</a>


<table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
	<thead>
		<tr>
			<td></td>
			<td>Name</td>
			<td>Role</td>
			<td>Email</td>
			<td>Actions</td>
		</tr>
	</thead>
	<tbody>
		@foreach($users as $user)
		<tr>
			<td></td>
			<td>{{ $user->name }}</td>
			<td>{{ $user->role->name ?? '' }}</td>
			<td>{{ $user->email }}</td>
			<td>
				{{-- @can('update', $user) --}}
				<a href="{{ route('users.edit', [$user->id]) }}" class="button is-primary">
					<i class="fa fa-pencil"></i>
				</a>
				{{-- @endcan --}}
				{{-- @can('delete', $user) --}}
				<form style="display: inline;" action="{{ route('users.destroy', [$user->id]) }}" method="POST">
					{{ csrf_field() }}
					{{ method_field('DELETE') }}
					<button type="submit" class="button is-danger">
						<i class="fa fa-trash"></i>
					</button>
				</form>
				{{-- @endcan --}}
			</td>
		</tr>
		@endforeach
	</tbody>
</table>

@endsection