routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index');

Auth::routes();

Route::get('/admin', 'Admin\IndexController@index')->name('admin');
Route::get('/admin/themes', 'Admin\ThemeController@index');
Route::post('/admin/themes/set', 'Admin\ThemeController@set');

Route::get('/admin/subsystems', 'Admin\SubsystemController@index');
Route::post('/admin/subsystems/{subsystem}/install', 'Admin\SubsystemController@install');
Route::post('/admin/subsystems/{subsystem}/enable', 'Admin\SubsystemController@enable');
Route::post('/admin/subsystems/{subsystem}/disable', 'Admin\SubsystemController@disable');

Route::resource('users', 'Admin\UserController');
Route::resource('roles', 'Admin\RoleController');

resources/views/admin/partials/menu.blade.php
<aside id="sidebar" class="menu column is-2">
	<div class="container">
		<p class="menu-label">
			General
		</p>
		<ul class="menu-list">
			<li><a href="{{ url('/admin') }}">Dashboard</a></li>
			@foreach($cruds as $crud)
			<li><a href="#">{{ $crud['labels']['name_plural'] }}</a></li>
			@endforeach
		</ul>
		<p class="menu-label">
			Administration
		</p>
		<ul class="menu-list">
			<li>
				<a>Users</a>
				<ul>
					<li><a href="{{ route('users.index') }}">Users</a></li>
					<li><a href="{{ route('roles.index') }}">Roles</a></li>
				</ul>
			</li>
			<li><a>Menus</a></li>
			<li><a class="is-active" href="{{ url('/admin/themes') }}">Themes</a></li>
			<li>
				<a class="" href="{{ url('/admin/subsystems') }}">Subsystems</a>
				<ul>
					<li><a>Routes</a></li>
					
				</ul>
			</li>
			
		</ul>
	</div>

</aside>